<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
      <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="LM-Kit.NET" />
    <PackageReference Include="LM-Kit.NET.Data.Connectors.PgVector" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="obs-websocket-dotnet" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Speech" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MARS.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MARS.Shared\MARS.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\onnx\duration_predictor.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\onnx\text_encoder.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\onnx\vector_estimator.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\onnx\vocoder.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
